<?php
/**
 * @category  ScandiPWA
 * @author    Mert Gulmus <mert.gulmus@scandiweb.com | info@scandiweb.com>
 * @author    Arturs Strucinskis <arturs.strucinskis@scandiweb.com | info@scandiweb.com>
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 * @copyright Copyright (c) 2022 Scandiweb, Inc (https://scandiweb.com)
 *
 * @var $block Scandiweb\DemoWidget\Block\Widget\Demo
 */
?>

<!--
    The value of type has to be the identical to what is used in WidgetFactory.component.plugin.js
    renderMap() function f.e.

    const renderMap = (member) => ({
        ...member,
        DemoWidget: {
            component: DemoWidget
        }
    });
-->
<widget type="DemoWidget"
        image="<?= $escaper->escapeHtml($block->getImage()) ?>"
        title="<?= $escaper->escapeHtml($block->getTitle()) ?>"
        wysiwyg="<?= $escaper->escapeHtml($block->getWysiwyg()) ?>"
        color="<?= $escaper->escapeHtml($block->getColor()) ?>"
        link="<?= $escaper->escapeHtml($block->getLink()) ?>"
        category="<?= $escaper->escapeHtml($block->getCategoryUrl()) ?>"
        date="<?= $escaper->escapeHtml($block->getDate()) ?>"
        phrase="<?= $escaper->escapeHtml($block->getPhrase()) ?>"
        textarea="<?= $escaper->escapeHtml($block->getTextarea()) ?>"

></widget>
<!--
    Please use full closing tags to all widget templates (*.phtml files).
    If we have the self-closing tags like <widget type="DemoWidget"/>
    the Scandipwa parser will not work as expected. So, please use
    <widget type="MyWidget"></widget> instead.
-->
