<?php
/**
 * @category  ScandiPWA
 * @author    Mert Gulmus <mert.gulmus@scandiweb.com | info@scandiweb.com>
 * @author    Arturs Strucinskis <arturs.strucinskis@scandiweb.com | info@scandiweb.com>
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 * @copyright Copyright (c) 2022 Scandiweb, Inc (https://scandiweb.com)
 *
 * @var Scandiweb\DemoWidget\Block\Widget\DemoWidget $block
 * @var Magento\Framework\Escaper $escaper
 */
?>

<?php
/**
 *   The value of type has to be the identical to what is used in WidgetFactory.component.plugin.js
 *   renderMap() function f.e.
 *
 *   const renderMap = (member) => ({
 *       ...member,
 *       DemoWidget: {
 *           component: DemoWidget
 *       }
 *   });
 *
 *   Please note that widget attributes with underscore (_) in the name like product_id
 *   Will be transformed to camel case e.g. productUrl in te ScandiPWA components
 */
?>
<widget type="DemoWidget"
        image="<?= $escaper->escapeHtml($block->getImage()) ?>"
        title="<?= $escaper->escapeHtml($block->getTitle()) ?>"
        wysiwyg="<?= $escaper->escapeHtml(base64_decode($block->getWysiwyg())) ?>"
        color="<?= $escaper->escapeHtml($block->getColor()) ?>"
        link="<?= $escaper->escapeHtml($block->getLink()) ?>"
        product_url="<?= $escaper->escapeHtml($block->getProductUrl()) ?>"
        category_url="<?= $escaper->escapeHtml($block->getCategoryUrl()) ?>"
        title_style="<?= $escaper->escapeHtml($block->getTitleStyle()) ?>"
        date="<?= $escaper->escapeHtml($block->getDate()) ?>"
        phrase="<?= $escaper->escapeHtml($block->getPhrase()) ?>"
        slider_id="<?= $escaper->escapeHtml($block->getSliderId()) ?>"
>
</widget>
<?php
/**
 *   Please use full closing tags to all widget templates (*.phtml files).
 *   If we have the self-closing tags like <widget type="DemoWidget"/>
 *   the Scandipwa parser will not work as expected. So, please use
 *   <widget type="DemoWidget"></widget> instead.
 */
?>
