<?php
/**
 * @category  ScandiPWA
 * @author    Mert Gulmus <mert.gulmus@scandiweb.com | info@scandiweb.com>
 * @author    Arturs Strucinskis <arturs.strucinskis@scandiweb.com | info@scandiweb.com>
 * @license   http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 * @copyright Copyright (c) 2022 Scandiweb, Inc (https://scandiweb.com)
 *
 * @var $block Scandiweb\DemoWidget\Block\Widget\Demo
 * We don't use this phtml file because we are using ScandiPWA way of rendering widgets
 * But if you want to render your widget using Magento way, you must use this file
 */
